From node:16.14.2 as build
 
 # building the frontend
 WORKDIR /app

 COPY . .
 Run npm i

 Run npm run build

 # copy the  build content and host it in web server
 FROM nginx:latest

 COPY --from=build /app/build/ /etc/nginx/html